### ISSUE TITLE
TestEquality

### ISSUE THREAD

**Issue by jonascarpay** [phadej/some#16]
What is the/is there a difference between `GEq` and [`TestEquality`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Type-Equality.html#v:testEquality)? I see you use it internally, is it just to avoid orphans?

**Comment by phadej** [comment]
See https://github.com/mokus0/dependent-sum/issues/31

**Comment by Ericson2314** [comment]
Depending on the outcome of https://github.com/haskell/core-libraries-committee/issues/21, `TestEquality` may be valid super class of `Eq` we could add.
