### ISSUE TITLE
GShow is the same as Show1 from base

### ISSUE THREAD

**Issue by Ericson2314** [phadej/some#19]
Unlike the other classes, there are no proof obligations that matching on the indices can satisfy. It's therefore not a "GADT class" as I understand them.

**Comment by phadej** [comment]
No the aren't the same.

```haskell
class Show1 f where
    liftShowsPrec :: (Int -> a -> ShowS) -> ([a] -> ShowS) ->
        Int -> f a -> ShowS

class GShow t where
    gshowsPrec :: -- nothing here
	Int -> t a -> ShowS
```

As a concrete example take

```haskell
data SBool (b :: Bool) where
    STrue  :: SBool 'True
    SFalse :: SBool 'False

instance GShow SBool where
    gshowsPrec _ STrue = showString "STrue"
    gshowsPrec _ SFalse = showString "SFalse"
```

**Comment by Ericson2314** [comment]
OK I'm sorry they are not exactly the same, I still don't think `GShow` adds any value.

First of all, you can implement each in terms of the other:
```haskell
class GShow t => Show1 f where
    liftShowsPrec _ _ = gshowsPrec

class Show1 f => GShow t where
    gshowsPrec = liftShowsPrec (\_ _ -> id) (\_ -> id)
```
And second of all, `Show1` offers more flexibility of the GADT index does in fact relate to the types of a field.

Now one could argue that is a bad thing, in which case I say `GShow` is obviated by the quantified constraint `forall a. Show (t a)`.

**Comment by phadej** [comment]
Show1 is not the same, see kinds and SBool example.

The quantified constraint is same however, but uses quantified constraints (GHC-8.6) when GShow works with GHC-7.0.

I don’t understand what is the problem GShow raises, more boilerplate?

**Comment by Ericson2314** [comment]
The problem is sort of an ecosystem split where some packages might use the quantified constraint and some would use GShow. My second PR just adds a basic default method, which I assume shouldn't be controversial. My third one adds in 8.6 <= the quantified constraint as a superclass to try to heal the ecosystem split: the idea is that you can't forget the show instances anymore of you write GShow, so you won't forget and more crates can work with you.
