### ISSUE TITLE
Port "Monoid newtypes"

### ISSUE THREAD

**Issue by 3noch** [phadej/some#29]
from https://github.com/obsidiansystems/dependent-sum/pull/37

**Comment by treeowl** [comment]
I've opened a PR as #30.

**Comment by phadej** [comment]
Won't port. As commented in #30:

> There is canonical Applicative f => Monoid (Some f) instance already. Use either Backwards or Dual to reverse it. Looks like I arrived to the same conclusion as in obsidiansystems/dependent-sum#37 (comment)
